name: ECS Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
   # branches: [ "main" ]
  #pull_request:
   # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
  id-token: write #Write permission required to authenticate with OIDC
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CheckoutRepositories:
    runs-on: ubuntu-latest
    environment: ECS
    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v6
        with:
          repository: IsaiahA17/SikrakenDevOps
          path: SikrakenDevOps
      
      - name: Checkout Sikraken Repo
        uses: actions/checkout@v6
        with:
          repository: IsaiahA17/Sikraken
          path: SikrakenDevOps/sikraken
          ref: ECS
      
      - name: Init PTC-Solver
        run: |
          git -C SikrakenDevOps/sikraken submodule update --init PTC-Solver
          
          # Move into the submodule
          cd SikrakenDevOps/sikraken/PTC-Solver          
          git fetch origin
          git checkout C_ver         
          
      - name: Configure AWS Credentials For ECR
        uses: aws-actions/configure-aws-credentials@main 
        with:
          role-to-assume: ${{ secrets.ECR_ACCESS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: sikraken/image-repo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f SikrakenDevOps/Dockerfiles/dockerfile SikrakenDevOps
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "image=$REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials For ECR
        uses: aws-actions/configure-aws-credentials@main 
        with:
          role-to-assume: ${{ secrets.ECR_ACCESS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@c804dfbdd57f713b6c079302a4c01db7017a36fc
        with:
          task-definition: ${{ vars.ECS_TASK_DEFINITION_PATH }}
          container-name: ${{ vars.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Register New Task
        id: register-task
        run: |
          echo "task-def=$(aws ecs register-task-definition --cli-input-json file://${{ steps.task-def.outputs.task-definition }} --query 'taskDefinition.taskDefinitionArn' --output text)" >>$GITHUB_OUTPUT
        
      - name: Execute ECS Tasks
        id: execute-ecs
        run: |
          chmod +x SikrakenDevOps/ECS/run_ecs.sh 
           OUTPUT=$(SikrakenDevOps/ECS/run_ecs.sh "${{ vars.ECS_CLUSTER }}" "${{ steps.register-task.outputs.task-def }}" "${{ vars.TASK_COUNT }}" "${{ vars.CATEGORY }}" "${{ vars.BUDGET }}")
          
          echo "$OUTPUT"
          TASK_ARNS=$(echo "$OUTPUT" | grep '^TASK_ARNS=' | cut -d= -f2-)
          echo "task_arns=$TASK_ARNS" >> $GITHUB_OUTPUT

      - name: Wait for ECS Tasks to Complete
        run: |
          CLUSTER="${{ vars.ECS_CLUSTER }}"
          TASK_ARNS="${{ steps.execute-ecs.outputs.task_arns }}"
      
          echo "Waiting for ECS tasks to complete..."
          echo "Tasks: $TASK_ARNS"
      
          while true; do
            STATUSES=$(aws ecs describe-tasks \
              --cluster "$CLUSTER" \
              --tasks $TASK_ARNS \
              --query 'tasks[].lastStatus' \
              --output text)
      
            echo "Current statuses: $STATUSES"
      
            if echo "$STATUSES" | grep -vqE 'PENDING|RUNNING'; then
              echo "All tasks have stopped."
              break
            fi
      
            sleep 20
          done
          
  InvokeLambda:
      environment: ECS
      needs: [CheckoutRepositories]
      runs-on: ubuntu-latest
      steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@main 
          with:
            role-to-assume: ${{ secrets.EC2_ACCESS_ROLE_ARN }}
            aws-region: eu-west-1
            
        - name: Invoke Lambda Function For Processing
          run: |
            aws lambda invoke --function-name ${{ secrets.LAMBDA_NAME }} \
            --cli-binary-format raw-in-base64-out \
            --payload '{ "Category": "${{ vars.CATEGORY }}" }' response.json
            URL=$(jq -r '.body | fromjson | .url' response.json) #Using the jq JSON command line processor to isolate the value of the url key
            echo "$URL" | awk -F '?' '{print $1}' #Using the text processor awk to try and remove the unnecessary parts of the html url
